name: Sync Simple Subtree

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:    # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-subtree:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with full Git history.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for subtree operations to work correctly

      # Configure Git with a default user for commits made by this action.
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Add the remote for the Simple repository.
      # This remote is added each time since GitHub Actions starts with a fresh clone.
      - name: Add remote for Simple repository
        run: |
          # Add the remote named 'simple'. Using HTTPS here; update to SSH if needed.
          git remote add simple https://github.com/filipelautert/simple.git || true
          git fetch simple

      # Pull updates from the Simple repository into the 'simple' subtree directory.
      - name: Pull updates from Simple subtree
        id: pull_subtree
        run: |
          # Store the current HEAD commit
          BEFORE_PULL=$(git rev-parse HEAD)
          
          # Perform the subtree pull and capture its output.  Fail on error.
          if ! OUTPUT=$(git subtree pull --prefix simple simple main 2>&1); then
            echo "Error during subtree pull:"
            echo "$OUTPUT"
            exit 1
          fi
          
          # Store the new HEAD commit
          AFTER_PULL=$(git rev-parse HEAD)
          
          # Compare commits to detect changes
          if [ "$BEFORE_PULL" != "$AFTER_PULL" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      # Create a pull request for the subtree updates if changes are detected.
      - name: Create Pull Request for subtree updates
        if: steps.pull_subtree.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore: sync Simple subtree updates'
          branch: 'sync-simple-updates'
          title: 'Sync updates from Simple repository'
          body: |
            This PR synchronizes the latest changes from the Simple repository
            into the subtree located in the `simple/` directory.